/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#b2f746",
        "surface-container-high": "#e2e7ff",
        "on-secondary-container": "#006172",
        error: "#ba1a1a",
        "surface-container-low": "#f2f3ff",
        "primary-fixed": "#e2dfff",
        "surface-container-lowest": "#ffffff",
        surface: "#faf8ff",
        "on-primary": "#ffffff",
        primary: "#3525cd",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#001f26",
        "on-primary-container": "#dad7ff",
        "surface-tint": "#4d44e3",
        tertiary: "#345000",
        "on-tertiary-container": "#abef3e",
        "surface-variant": "#dae2fd",
        "surface-dim": "#d2d9f4",
        secondary: "#00687a",
        outline: "#777587",
        "tertiary-container": "#466a00",
        "secondary-container": "#57dffe",
        "inverse-primary": "#c3c0ff",
        "secondary-fixed-dim": "#4cd7f6",
        "on-background": "#131b2e",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#3323cc",
        "inverse-surface": "#283044",
        "on-surface-variant": "#464555",
        "secondary-fixed": "#acedff",
        "tertiary-fixed-dim": "#98da27",
        "on-tertiary-fixed": "#121f00",
        "on-primary-fixed": "#0f0069",
        "outline-variant": "#c7c4d8",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#c3c0ff",
        "on-tertiary-fixed-variant": "#334f00",
        "on-error": "#ffffff",
        "surface-container-highest": "#dae2fd",
        "on-secondary": "#ffffff",
        "surface-bright": "#faf8ff",
        "primary-container": "#4f46e5",
        "inverse-on-surface": "#eef0ff",
        "on-surface": "#131b2e",
        background: "#faf8ff",
        "surface-container": "#eaedff",
        "on-secondary-fixed-variant": "#004e5c",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope"],
        body: ["Inter"],
        label: ["Inter"],
      },
    },
  },
  plugins: [],
};
